#!/usr/bin/osascript

--set hostnames to {"in-time.me", "in-time.me", "in-time.me", "in-time.me"}
on run argv
  copy argv to hostnames
  launch "iTerm"

  tell application "iTerm"
    activate

    -- ssh in split panes to my queue processor hosts
    set myterm to (make new terminal)
    tell myterm
      launch session "Default Session"

      -- make the window fullscreen
      tell i term application "System Events" to key code 36 using command down
      delay 2
      if length of hostnames is not 1
        -- split horizontally
        tell i term application "System Events" to keystroke "d" using {command down, shift down}
        -- move to upper split
        tell i term application "System Events" to keystroke "[" using command down
      end if

      set num_hosts to count of hostnames

      repeat with n from 1 to num_hosts
        if n - 1 is num_hosts / 2 as integer then
          -- move to lower split
          tell i term application "System Events" to keystroke "]" using command down
        else if n > 1 then
          -- split vertically
          --tell i term application
          --  keystroke "d" using {command down, shift down}
          --end tell
          --tell i term application "System Events" to keystroke "d" using {command down, shift down}
          tell i term application "System Events" to keystroke "d" using command down
        end if
        delay 1
        tell the current session to write text "ssh " & (item n of hostnames)
      end repeat
      if length of hostnames is not 1
        delay 1
        tell i term application "System Events"
          keystroke "I" using command down
        end tell
        tell i term application "System Events" to keystroke return
      end if
    end tell
  end tell
end run
